version: "3.6"
services:
  webhook:
    image: nodejs:14.16.1-alpine3.10
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    environment:
      DB_MYSQL_NAME: hasura
      DB_MYSQL_PORT: 5432 # set to "false" to disable console
      DB_MYSQL_HOST: 45.32.120.55
      DB_MYSQL_USER: postgres
      DB_MYSQL_PASSWD: Tuantu123@
  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-alpha.10
    ports:
      - "8092:8888"
    restart: always
    depends_on:
      - webhook
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:Tuantu123@@45.32.120.55:5432/hasura
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: f3ccab3e8cb12b90fabf55eb276457cb9f9fabcc121783fe4335f677ed7a5f0bae
      HASURA_GRAPHQL_AUTH_HOOK: http://webhook:5500/wh # for docker mac - https://hasura.io/docs/latest/graphql/core/guides/docker-networking.html#docker-networking
      HASURA_GRAPHQL_AUTH_HOOK_MODE: GET
volumes:
  db_data:
